[kernels]

  [[kernels.kernel]]
    name = "emoji.v1.kernel.Emoji"
    num_replicas = 1
    max_concurrent_queries = 4

    [kernels.kernel.resources]
      cpu = 0.1

  [[kernels.kernel]]
    name = "generate.v1.kernel.Generate"
    num_replicas = 1
    max_concurrent_queries = 4

    [kernels.kernel.resources]
      gpu = 0.4

  [[kernels.kernel]]
    name = "summarize.v1.kernel.Summarize"
    num_replicas = 1
    max_concurrent_queries = 4

    [kernels.kernel.resources]
      gpu = 0.09

  [[kernels.kernel]]
    name = "score.v1.kernel.Score"
    num_replicas = 1
    max_concurrent_queries = 4

    [kernels.kernel.resources]
      gpu = 0.05

  [[kernels.kernel]]
    name = "tts.v1.kernel.TTS"
    num_replicas = 1
    max_concurrent_queries = 4

    [kernels.kernel.resources]
      gpu = 0.01

    [kernels.kernel.configuration]
      sox = 'C:\Program Files (x86)\sox-14-4-2'
    
  [[kernels.kernel]]
    name = "tokenizer.v1.kernel.Tokenizer"
    num_replicas = 1
    max_concurrent_queries = 4

    [kernels.kernel.resources]
      gpu = 0.01